# Generated by Django 5.0.6 on 2025-12-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_daily_bonus_claimed_user_daily_earn_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPXTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100, unique=True)),
                ('event', models.CharField(default='complete', max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('amount_local', models.IntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
