# Generated by Django 5.0.6 on 2025-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cpxtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('offerwall', 'Offerwall'), ('scratch_card', 'Scratch Card'), ('spin_wheel', 'Spin Wheel'), ('puzzle', 'Puzzle')], max_length=20),
        ),
    ]
