"""
Django settings for earning_backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file (for local development)
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Core security / environment config
# ---------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# In production set DJANGO_DEBUG=False in env
# Default to False for security (must explicitly set to True for development)
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# In production set DJANGO_ALLOWED_HOSTS to your domain(s), comma-separated
# e.g. "earning-backend-production.up.railway.app"
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")

# Production security settings
# Railway handles HTTPS termination at the proxy level
# We need to trust the proxy headers to avoid redirect loops
if not DEBUG:
    # Trust Railway's proxy to handle HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Disable SSL redirect since Railway handles it
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF / CORS – add your Vercel URL after you deploy frontend
# e.g. "https://nepearn-frontend.vercel.app"
# Initialize logger first for CORS logging
import logging
_cors_logger = logging.getLogger(__name__)

# Parse CORS origins from environment variable or use defaults
_cors_origins_env = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,https://earning-frontend.vercel.app,https://nepearn.vercel.app"
)

# Split by comma and strip whitespace from each origin
# Handle both comma and space-separated values
_cors_origins_list = []
if _cors_origins_env:
    # Split by comma first
    for item in _cors_origins_env.split(","):
        # Then split by space in case there are spaces
        for origin in item.split():
            origin = origin.strip()
            if origin:
                _cors_origins_list.append(origin)

CORS_ALLOWED_ORIGINS = _cors_origins_list if _cors_origins_list else []

# Fallback: If CORS_ALLOWED_ORIGINS is empty or invalid, allow common origins
if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "https://earning-frontend.vercel.app",
        "https://nepearn.vercel.app",
    ]
    _cors_logger.warning("CORS_ALLOWED_ORIGINS was empty, using fallback defaults")

_csrf_origins_env = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://earning-backend-production.up.railway.app,https://earning-frontend.vercel.app,https://nepearn.vercel.app"
)
# Split by comma and strip whitespace from each origin
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_env.split(",") if origin.strip()]

# Fallback: If CSRF_TRUSTED_ORIGINS is empty, use defaults
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        "https://earning-backend-production.up.railway.app",
        "https://earning-frontend.vercel.app",
        "https://nepearn.vercel.app",
    ]

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for better compatibility
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Explicitly allow preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Ensure CORS middleware handles all origins properly
# This helps with OPTIONS preflight requests
CORS_URLS_REGEX = r'^/api/.*$'

# Log CORS configuration for debugging (using the logger we created earlier)
_cors_logger.info("=" * 50)
_cors_logger.info("CORS Configuration:")
_cors_logger.info(f"  CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")
_cors_logger.info(f"  CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
_cors_logger.info(f"  CORS_ALLOW_CREDENTIALS: {CORS_ALLOW_CREDENTIALS}")
_cors_logger.info(f"  CORS_ALLOW_METHODS: {CORS_ALLOW_METHODS}")
_cors_logger.info("=" * 50)

# ---------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------

INSTALLED_APPS = [
    # Jazzmin must be before django.contrib.admin
    "jazzmin",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",

    # Local
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "earning_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "earning_backend.wsgi.application"

# ---------------------------------------------------------------------
# Database
#   - Locally: use SQLite (simpler, no Postgres needed)
#   - On Railway: use Postgres via env vars
# ---------------------------------------------------------------------

if os.environ.get("RAILWAY_ENVIRONMENT"):  # True on Railway
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    # Local development: SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------
# Auth / REST / JWT
# ---------------------------------------------------------------------

AUTH_USER_MODEL = "core.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ---------------------------------------------------------------------
# Logging (helpful for Railway logs)
# ---------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if DEBUG else "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

CPX_APP_ID = os.getenv("CPX_APP_ID", "")
CPX_SECURITY_HASH = os.getenv("CPX_SECURITY_HASH", "cH0T7KHiYJBFKLFqc0k22HICZ1B33")
CPX_CURRENCY_FACTOR = int(os.getenv("CPX_CURRENCY_FACTOR", "1000"))
CPX_SECRET = os.environ.get("CPX_SECRET", "")
CPX_REQUIRE_SECURE_HASH = os.getenv("CPX_REQUIRE_SECURE_HASH", "false").lower() == "true"

# ---------------------------------------------------------------------
# JAZZMIN ADMIN THEME CONFIGURATION - Professional & Attractive
# ---------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # Title on the brand (19 chars max)
    "site_brand": "💰 NepEarn Admin",
    "site_logo": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to NepEarn Admin Panel",
    "login_logo": None,
    "login_logo_dark": None,
    
    # Copyright on the footer
    "copyright": "© 2024 NepEarn. All rights reserved.",
    
    # The model admin to search from the search bar
    "search_model": ["auth.User", "core.WithdrawRequest", "core.Task"],
    
    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "🏠 Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "🌐 View Site", "url": "/", "new_window": True},
        {"name": "📊 Analytics", "url": "admin:core_withdrawrequest_changelist", "permissions": ["core.view_withdrawrequest"]},
    ],
    
    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "🔒 Change Password", "url": "admin:password_change", "icon": "fas fa-key"},
        {"name": "📝 Profile", "url": "admin:auth_user_change", "icon": "fas fa-user", "permissions": ["auth.view_user"]},
    ],
    
    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu
    "hide_apps": [],
    
    # Hide these models when generating side menu
    "hide_models": [],
    
    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": ["auth", "core"],
    
    # Custom links to append to app groups
    "custom_links": {
        "core": [{
            "name": "💰 Pending Withdrawals",
            "url": "admin:core_withdrawrequest_changelist?status__exact=pending",
            "icon": "fas fa-clock",
            "permissions": ["core.view_withdrawrequest"]
        }, {
            "name": "📊 Dashboard Stats",
            "url": "admin:index",
            "icon": "fas fa-chart-bar",
        }]
    },
    
    # Custom icons for models - Professional icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-circle",
        "auth.Group": "fas fa-users",
        "core.User": "fas fa-user-tie",
        "core.Task": "fas fa-tasks",
        "core.UserTask": "fas fa-clipboard-check",
        "core.WithdrawRequest": "fas fa-money-bill-wave",
        "core.WalletTransaction": "fas fa-wallet",
        "core.Settings": "fas fa-cogs",
        "core.FraudEvent": "fas fa-shield-alt",
        "core.Achievement": "fas fa-trophy",
        "core.DailyChallenge": "fas fa-calendar-check",
    },
    
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # Related Modal #
    #################
    "related_modal_active": True,
    
    #############
    # UI Tweaks #
    #############
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "core.WithdrawRequest": "horizontal_tabs",
    },
    
    # Custom CSS for additional styling
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}